# Every PR needs two approvals from Zalando employees.
approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          # Only "zalando" allowed here!
          - zalando
X-Zalando-Team: "automata"
